services:
  test:
    build: ./
    environment:
      - MTA_HOST=mta-in
      - MDA_API_SECRET=mda-secret
    command: pytest -vvs .
    volumes:
      - ./tests:/app
    ports:
      - "8000:8000"
    networks:
      - mta_in_network

  mta-in:
    build: ./postfix
    environment:
      - MDA_API_BASE_URL=http://test:8000/api/mail/
      - MDA_API_SECRET=mda-secret
      - MESSAGE_SIZE_LIMIT=30000000
    networks:
      - mta_in_network
    ports:
      - "25:25"

networks:
  mta_in_network:
    driver: bridge 