services:
  test:
    build: ./
    environment:
      - MTA_HOST=mta-in
      - MDA_API_SECRET=mda-secret
    command: pytest -vvs .
    volumes:
      - ./tests:/app
      - ./postfix:/app/src_postfix
    ports:
      - "8000:8000"
    networks:
      - mta_in_network
    # wait for mta-in to be ready
    depends_on:
      mta-in:
        condition: service_healthy

  mta-in:
    build: ./postfix
    environment:
      - MDA_API_BASE_URL=http://test:8000/api/mail/
      - MDA_API_SECRET=mda-secret
      - MDA_API_TIMEOUT=2
      - MESSAGE_SIZE_LIMIT=30000000
    networks:
      - mta_in_network
    ports:
      - "25:25"
    healthcheck:
      test: netstat -l | grep smtp
      interval: 1s
      timeout: 10s
      retries: 30

networks:
  mta_in_network:
    driver: bridge
