from typing import Optional
from core.models import Thread
from core.services.ai_service import AIService
from core.ai.thread_summarizer import get_messages_from_thread, Message

def generate_answer_mail(thread: Optional[Thread], draft: str, prompt: str) -> str:
    """
    Generates an answer to a thread using the ALBERT model.
    Args:
        thread (Thread): Thread to answer.
    Returns:
        str: Answer to the thread.
    """

    # Prepare the prompt for the AI model
    messages = get_messages_from_thread(thread) if thread else []
    conversation_text = "\n\n".join([str(message) for message in messages]) if messages else ""
    prompt_query = "Tu es un assistant intelligent qui est intégré dans une boîte mail. Tu dois fournir une réponse à la demande suivante. La réponse attendue est un mail rédigé assez pro, sauf si c'est une réponse à un mail qui a lui même un autre style. Notamment réutilise la même formule de salutation si présente (Bonjour, Hello, Salut, Coucou, etc...)."
    thread_rules = "Voici en contexte les mails précédents du thread : \n\n"
    answer_rules = "Ta réponse doit être uniquement le corps du message (ne mentionne pas l'objet ni les destinataires) NE mets PAS de guillemets autour de ta réponse"
    prompt = prompt_query + draft + prompt
    if messages:
        prompt += thread_rules + conversation_text
    prompt += answer_rules + "\n\nRéponse à la demande ci-dessus :"
    # Make the API call to get the summary
    answer = AIService().call_ai_api(prompt)
    return answer

def generate_new_mail(draft: str, prompt: str) -> str:
    """
    Generates a new mail using the ALBERT model.
    Args:
        draft (Str): Message draft.
        prompt (Str): user prompt for the AI assistant.
    Returns:
        str: Message generated by the AI assistant.
    """

    role = "Tu es un assistant intégré dans la zone d'écriture des mails dans une boîte mail. TA REPONSE NE DOIT JAMAIS FAIRE TE FAIRE APPARAITRE, ne justifie jamais pourquoi tu donne une certaine réponse, tu ne dois jamais te mentionner (pas de 'assistant' dans tes réponses)."
    answer_rules = "\n\n LA REPONSE ATTENDUE EST UN CORPS DE MAIL rédigé assez pro. Ta réponse doit être UNIQUEMENT le corps du message (ne mentionne pas l'objet ni les destinataires) NE mets PAS de guillemets autour de ta réponse"
    global_prompt = role + answer_rules + "\n\nVoici le brouillon de message de l'utilisateur :\n" + draft + "\n\nVoici la demande de l'utilisateur :\n" + prompt + "\n\nRéponse à la demande ci-dessus : "
    answer = AIService().call_ai_api(global_prompt)
    return answer