import os
import json
import random
from typing import Optional
from core.models import Thread
from core.services.ai_service import AIService
from core.ai.thread_summarizer import get_messages_from_thread, Message

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROMPTS_FILE_PATH = os.path.join(BASE_DIR, "ai_prompts.json")
with open(PROMPTS_FILE_PATH, "r") as f:
    AI_PROMPTS = json.load(f)


def get_random_prompt(prompt_type: str = None):
    if prompt_type:
        filtered_prompts = [p for p in AI_PROMPTS if p["type"] == prompt_type]
    prompt_selected = random.choice(filtered_prompts)
    return prompt_selected["content"], prompt_selected["id"]

def generate_answer_mail(thread: Optional[Thread], draft: str, prompt: str, name: str) -> str:
    """
    Generates an answer to a thread using the ALBERT model.
    Args:
        thread (Thread): Thread to answer.
    Returns:
        str: Answer to the thread.
    """

    # Prepare the prompt for the AI model
    messages = get_messages_from_thread(thread) if thread else []
    conversation_text = "\n\n".join([str(message) for message in messages]) if messages else ""
    
    selected_prompt, prompt_id = get_random_prompt("answer_mail")

    role = selected_prompt["role"]
    answer_rules = selected_prompt["answer_rules"]
    global_prompt_template = selected_prompt["global_prompt_template"]
    example = selected_prompt["example"]

    global_prompt = global_prompt_template.format(
        role=role,
        answer_rules=answer_rules,
        thread_context=conversation_text,
        example=example,
        draft=draft,
        name=name
    )
    answer = AIService().call_ai_api_with_extra_instructions(global_prompt, prompt)
    return {
        "answer": answer,
        "prompt_id": prompt_id
    }


def generate_new_mail(draft: str, prompt: str, name: str) -> str:
    """
    Generates a new mail using the ALBERT model.
    Args:
        draft (Str): Message draft.
        prompt (Str): user prompt for the AI assistant.
    Returns:
        str: Message generated by the AI assistant.
    """
    selected_prompt, prompt_id = get_random_prompt("new_mail")

    role = selected_prompt["role"]
    answer_rules = selected_prompt["answer_rules"]
    global_prompt_template = selected_prompt["global_prompt_template"]
    example = selected_prompt["example"]

    global_prompt = global_prompt_template.format(
        role=role,
        answer_rules=answer_rules,
        example=example,
        draft=draft,
        name=name
    )
    answer = AIService().call_ai_api_with_extra_instructions(global_prompt, prompt)
    return {
        "message": answer,
        "prompt_id": prompt_id
    }