services:
  test:
    build: ./tests
    environment:
      - MTA_HOST=mta
      - MDA_API_SECRET=mda-secret
    command: pytest -vvs .
    volumes:
      - ./tests:/app
    ports:
      - "8000:8000"
    networks:
      - mta_network

  mta:
    build: ./postfix
    environment:
      - MDA_API_URL=http://test:8000/api/mail
      - REGIE_API_URL=http://test:8000/api/regie/mailbox
      - MDA_API_SECRET=mda-secret
      - MESSAGE_SIZE_LIMIT=30000000
    networks:
      - mta_network
    ports:
      - "25:25"

networks:
  mta_network:
    driver: bridge 