# Generated by Django 5.1.8 on 2025-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="summary"),
        ),
    ]
