# Generated by Django 5.1.8 on 2025-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mailbox_is_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='auto_labellisation',
            field=models.BooleanField(default=True, help_text='Whether this label should be automatically applied by AI', verbose_name='auto labellisation'),
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the label, used by AI to understand its purpose', max_length=255, verbose_name='description'),
        ),
    ]
