# Generated by Django 5.1.8 on 2025-07-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_thread_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the label, used by AI to understand its purpose', max_length=255, verbose_name='description'),
        ),
    ]
