# Generated by Django 5.1.8 on 2025-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_label_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='auto_labellisation',
            field=models.BooleanField(default=False, help_text='Whether this label should be automatically applied by AI', verbose_name='auto labellisation'),
        ),
    ]
