# Generated by Django 5.1.8 on 2025-07-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_label_description_label_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='label',
            name='is_auto',
            field=models.BooleanField(default=True, help_text='Whether this label should be automatically applied by AI', verbose_name='auto labeling'),
        ),
    ]
