# Generated by Django 5.1.8 on 2025-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_label_auto_labellisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='auto_labellisation',
            field=models.BooleanField(default=True, help_text='Whether this label should be automatically applied by AI', verbose_name='auto labellisation'),
        ),
    ]
