# Generated by Django 5.1.8 on 2025-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_label_is_enabled_label_is_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dkimkey',
            name='selector',
            field=models.CharField(help_text="DKIM selector (e.g., 'default', 'mail')", max_length=255, verbose_name='selector'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(help_text="Name of the label/folder (can use slashes for hierarchy, e.g. 'Work/Projects')", max_length=255, verbose_name='name'),
        ),
    ]
