# Generated by Django 5.1.8 on 2025-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dkimkey_selector_alter_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='is_auto',
            field=models.BooleanField(default=False, help_text='Whether this label should be automatically applied by AI', verbose_name='auto labeling'),
        ),
    ]
