# Generated by Django 5.1.8 on 2025-06-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_thread_count_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='summary'),
        ),
    ]
