# Generated by Django 5.1.8 on 2025-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_label_options_alter_message_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='summary'),
        ),
    ]
