# Generated by Django 5.1.8 on 2025-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_thread_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='tags'),
        ),
    ]
