# Generated by Django 5.1.8 on 2025-07-18 23:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_thread_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('prompt_id', models.IntegerField(verbose_name='prompt id')),
                ('prompt_type', models.CharField(help_text='Type of prompt: "new_mail" or "answer_mail"', max_length=50, verbose_name='prompt type')),
                ('accepted', models.BooleanField(verbose_name='liked')),
            ],
            options={
                'verbose_name': 'prompt evaluation',
                'verbose_name_plural': 'prompt evaluations',
                'db_table': 'messages_promptevaluation',
            },
        ),
    ]
