# Generated by Django 5.1.8 on 2025-07-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_label_options_alter_message_subject_and_more'),
        ('core', '0019_thread_tags'),
    ]

    operations = [
    ]
