# Generated by Django 5.1.8 on 2025-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20250709_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='prompt',
            field=models.CharField(default='', help_text='Prompt for the LLM', max_length=255, verbose_name='prompt'),
        ),
    ]
