# Generated by Django 5.1.8 on 2025-07-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_label_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='prompt',
        ),
    ]
