# Generated by Django 5.1.8 on 2025-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_label_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='prompt',
            field=models.CharField(default='DEFAULT_VALUE', help_text='Prompt for the LLM', max_length=255, verbose_name='prompt'),
        ),
    ]
