# Generated by Django 5.1.8 on 2025-07-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_label_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='tags',
        ),
    ]
